### ISSUE TITLE
Identify variables appropriate for clustering

### ISSUE THREAD

**Issue by claussian** [claussian/hh-typology#1]
Identify and summarize the set of variables to be used for clustering

**Comment by claussian** [comment]
Opinion: variables to be used for clustering should be directly related to balance sheet questions, and not on demographics. We cluster households according to balance sheet positions, _then_ see what their demographic are like.

See: http://www.pewinternet.org/2009/03/25/the-mobile-difference/

**Comment by u7st69** [comment]
![image](https://cloud.githubusercontent.com/assets/6746618/7100668/b909e2c2-e026-11e4-8d99-de9319829a27.png)

**Comment by jarvisc1** [comment]
These are the variables I've looked at clusters with. I think quite a few of them are telling a similar story so could be removed. It might be possible to figure some of the missing values of some based on the others? The last two I've ignored because they don't come into play until 2009 so not so useful for us  

![image](https://cloud.githubusercontent.com/assets/6746618/7100674/0e0110c0-e027-11e4-85a9-22782c273463.png)

**Comment by claussian** [comment]
Thinking about this again, there seems to be **three** types of variables:
1. 'Pure' balance sheet questions (e.g. how much disposable income)
2. Questions on financial attitudes (e.g. are you going to change the amount that you save)
3. Demographics

Type 1 variables are 'factual' can be converted into ordinal variables. These can be added up into a straightforward score to assess the household's financial position.

Type 2 variables are the ones that are more 'opinion-based' and categorical. These are the ones that may be worth clustering.

Type 3 variables are also factual.

See: https://docs.google.com/spreadsheets/d/1XDHEFWAS-pSz2Zl1LQgU_rwlOrMFg_CH6x5m6dXBLrs/edit?usp=sharing

**Comment by claussian** [comment]
Gather all Type 2 variables for 2007 face-to-face dataset

Consider patterns of missingness and decide on data subset that takes care of missingness

**Comment by claussian** [comment]
Many of the 'juicy' Type 2 variables are found only in post-2009. Think we should cluster 2009-2011 datasets, can describe it as households' responses to the Recession

**Comment by claussian** [comment]
How to deal with 'not applicable' or blank observations?

**Rule of thumb:** for categorical variables split into a series of binaries (e.g. xphdr1-12), 'not applicable' or blank observations usually result when respondent does not answer 'yes' to ANY of these variables. So effectively respondent has 'no' for all variables in that set. Crucially, these sets of variables allow multiple 'yes' per set.

We may convert 'not applicable' or blank to 'no' in such instances. However when the % of NA or blank is very high it may be more appropriate to remove the variable as they are not very informative.

However, when 'not applicable' or blank is found in a pure categorical variable they are not interchangeable with 'no'. In such cases we may have to remove the NA or blank observations.

**Comment by claussian** [comment]
Identified 30, 60 and 33 variables respectively for 2009-2011 datasets. Further selection of variables will be based on results from clustering
