### ISSUE TITLE
Identify variables to be used for visualizing

### ISSUE THREAD

**Issue by claussian** [claussian/hh-typology#2]
Identify and summarize the set of variables related to household debt positions

**Comment by claussian** [comment]
Consider the debt-to-income ratio distribution, else use a composite wealth score to highlight differences between the clusters

**Comment by claussian** [comment]
**User choices at the UI will create the following variables:**
1. input$year. values=2009,2010,2011
2. input$clustnum. values=Two,Four

**Combinations of the above variables will activate further variables that can be passed to server.R**
1. 2009 + Two = input$hh09_two. values=1,2
2. 2009 + Four = input$hh09_four. values=1,2,3,4
3. 2010 + Two = input$hh10_two. values=1,2
4. 2010 + Four = no variable as evidence for four clusters is weak
5. 2011 + Two = input$hh11_two. values=1,2
6. 2011 + Four = input$hh09_four. values=1,2,3,4

Pass these input arguments to server.R to activate the appropriate clusters

**Comment by claussian** [comment]
Three main components to visualize:
1. MDS plot, highlight clusters according to user choice
2. Financial balance sheet position. Income, debt-to-income ratio. Show cluster average compared to survey population average
3. Demographic variables. Group variables together according to a theme e.g. family. Again, show cluster average compared to survey population average

**Comment by jarvisc1** [comment]
On the Demographic tab we have a map and then bar charts which will change according to the selection of 

input$demographic

**Comment by claussian** [comment]
All elements mentioned above included. For financial variables, we did not use a composite score but overlaid cluster points directly with income/debt data.
