### ISSUE TITLE
Clustering techniques

### ISSUE THREAD

**Issue by claussian** [claussian/hh-typology#3]
1. Dissimilarity matrix using Gower's distance in daisy function (https://stat.ethz.ch/R-manual/R-patched/library/cluster/html/daisy.html) + cmdscale
2. Function MCA in package factomineR (http://factominer.free.fr/classical-methods/multiple-correspondence-analysis.html)

**Comment by claussian** [comment]
**How to decide on whether clusters are appropriate?**

**Descriptive**: Chart the clusters in terms of attitude variables. See whether a natural story falls out

**Comment by jarvisc1** [comment]
Look at association of demographic and balance sheet variables with the clusters for 2009. See if we can predict the clusters. 

Consider if we can predict the groupings in future years based on 09 custers

**Comment by claussian** [comment]
Based on 2009 and 2011 data, two-cluster groupings seem to reflect a clear division between financially secure and insecure households. The fact that the division persists in spite of different set of variables between the years suggests that this clustering is robust.

To do the same for 2010 (initial results look promising).

Further action: Explore >2 clusters

**Comment by jarvisc1** [comment]
Looking at 2009 clusters. 

I started looking at clusters within cluster 1. I removed the 2nd cluster of data and ran the pam on  the remaining 1st cluster data. I'm seeing quite a bit of seperation when looking at 3 groups

![image](https://cloud.githubusercontent.com/assets/6746618/7198979/c2dafc66-e4e8-11e4-91ab-342a66d01c9a.png)

When it's two groups there are two obvious clusters I can see visually but the algorithm doesn't seem to be splitting in that way so perhaps something we can't see in 2 dimensions

![image](https://cloud.githubusercontent.com/assets/6746618/7198977/b5302b22-e4e8-11e4-9ce0-f17d8e4b6d90.png)

3 groups with labels so you can relate to the next plot

![image](https://cloud.githubusercontent.com/assets/6746618/7199063/866a9146-e4e9-11e4-9e48-7f14c2685c81.png)

Then for Xphsdf Cluster 2 is definitely different. So there is some suggestion that we might have a 2 clusters within Cluster 1. 

![image](https://cloud.githubusercontent.com/assets/6746618/7199003/f9696cc2-e4e8-11e4-862c-dd53ded468af.png)

I did the same exploring in cluster 2 and didn't find much separation. 
for example in looking at xphsdf

![image](https://cloud.githubusercontent.com/assets/6746618/7199030/3f498d58-e4e9-11e4-9a34-d9b38192dca9.png)

**Comment by jarvisc1** [comment]
I'm seeing Two groups with four overall subgroups. Rich-poor Divide with a further Rich divide

#### Group 1 not worried about House

Cluster 1: Bills- Mostly Keeping up without problems but struggle from time to time,
Cluster 2: Bills- Never really struggle
Cluster 3: Bills- Most struggle from time to time some are in a constant struggle

#### Group 2 Worried about paying for house

Cluster 4: Bills- The people who are really struggling

Problems keeping up with house payments
![image](https://cloud.githubusercontent.com/assets/6746618/7200973/5ea8748c-e4fa-11e4-930e-0ce709478e3d.png)

Problem keeping up with bill payments
![image](https://cloud.githubusercontent.com/assets/6746618/7200989/7b6e1e78-e4fa-11e4-9c73-670d94c4c58d.png)

**Comment by jarvisc1** [comment]
Well Two groups with four subgroups

#Group 1 not worries about House
Cluster 1: Bills- Mostly Keeping up without problems but struggle from time to time,
Cluster 2: Bills- Never really struggle
Cluster 3: Bills- Most struggle from time to time some are in a constant struggle

#Group 2 Worried about paying for house
Cluster 4: Bills- The people who are really struggling

**Comment by claussian** [comment]
Households can generally be divided into Financially Secure vs. Insecure households, but further clustering reveals interesting differences within each main cluster.

Please read the [wiki](https://github.com/claussian/hh-typology/wiki/Four-cluster-characterization:-2011) for a tentative four-cluster characterization of households in 2011.

**Comment by jarvisc1** [comment]
I think we can close this now.
