### ISSUE TITLE
Determine layout for shiny viz

### ISSUE THREAD

**Issue by claussian** [claussian/hh-typology#4]
I have sketched a draft of the proposed layout (mockup_1.jpg). User will select a year of interest, upon which a conditional panel will appear to choose the cluster of interest. Selecting cluster will reveal several items in the main tab:

1) Cluster position on MDS plot (good to highlight the natural clustering)
2) Responses to 5-6 key financial attitude questions, compare to survey population
3) Corresponding balance sheet responses (e.g. income, debt to income ratio, no.of unsecured debts)

A second tab will be available to highlight demographics of this cluster (e.g. age range, marital status, geographical location).

Thoughts?

**Comment by jarvisc1** [comment]
What if you can choose year, cluster or both. 

If only cluster, then
1 change in balance sheet responses over the years
2 change demographic questions over each year

not 100% convinced myself.

**Comment by claussian** [comment]
The flow is as follows:
1. Choose year
2. Choose no. of clusters (2 or 4) > Cluster names will appear according to year&number combi
3. Optional: choose demographics tab > Choose which demographic panel to show (group demog variables together)

**Comment by claussian** [comment]
Layout settled.
