### ISSUE TITLE
Chloropleth map for UK regions

### ISSUE THREAD

**Issue by claussian** [claussian/hh-typology#5]
One of the interesting demographic features that we should plot is the distribution of each cluster across UK regions. We can use the %difference in region membership between cluster and total survey population (e.g. 30% of survey population is in London, but 35% of Cluster 1 is in London, so 35-30=+5% London for Cluster 1).

But first, we need shapefiles for UK Government Office regions!
- East Midlands
- Eastern
- London
- North East
- North West
- Scotland
- South East
- South West
- Wales
- West Midlands
- Yorks and Humber

**Comment by jarvisc1** [comment]
Leave getting the shp files to me I'll have a look what I already have.  Sounds like a great idea.

**Comment by jarvisc1** [comment]
I'll put together some code for a map I already have some from another project so should be fairly quick. I'll send on tomorrow(later today for you)

**Comment by jarvisc1** [comment]
Shape File is made and uploaded called boe.Rdata. 
I create a choloromap programme with 2 examples I think the actually map can be explored a bit more in the visualisation process so I'll close this issue.
